#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jul 02, 2022 12:38:45 AM CEST  platform: Darwin
#    Jul 02, 2022 08:16:36 AM CEST  platform: Darwin

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import motionapp_gui
from pubsub import pub

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    global _top1, _w1
    _top1 = root
    _w1 = motionapp_gui.Toplevel1(_top1)
    initial_values()
    root.mainloop()

def initial_values():
    _w1.x_pos_org.set(0.0)
    _w1.y_pos_org.set(0.0)
    _w1.theta_org.set(90.0)
    _w1.body_width.set(1.0)
    _w1.acceleration_left.set(0.0)
    _w1.acceleration_right.set(0.0)
    _w1.velocity_left.set(2.5)
    _w1.velocity_right.set(2.4)
    _w1.animation_duration.set(2)
    _w1.dead_reckoning_interval.set(0.1)
    _w1.dead_reckoning_interval.set(0.5)

    pub.subscribe(draw, 'draw')

# Gui callback-function definitions

def original_position_changed(*args):
    x = _w1.x_pos_org.get()
    y = _w1.y_pos_org.get()
    theta = _w1.theta_org.get()
    value = (x, y, theta)
    pub.sendMessage('original_position_changed', value=value)

def acceleration_changed(*args):
    left = _w1.acceleration_left.get()
    right = _w1.acceleration_right.get()
    value = (left, right)
    pub.sendMessage('acceleration_changed', value=value)

def velocity_changed(*args):
    left = _w1.velocity_left.get()
    right = _w1.velocity_right.get()
    value = (left, right)
    pub.sendMessage('velocity_changed', value=value)

def body_width_changed(value):
    pub.sendMessage('width_changed', value=value)

def simulation_changed(value):
    duration = _w1.duration.get()
    interval = _w1.dead_reckoning_interval.get()
    value = (duration, interval)
    pub.sendMessage('simulation_changed', value=value)

def interval_changed(value):
    pub.sendMessage('interval_changed', value=value)

def draw(value):
    text = _w1.Canvas1.create_text(10, 10, text=value, font='Helvetica 15')
    _w1.Canvas1.itemconfigure(text, state=tk.DISABLED, anchor=tk.NW)

if __name__ == '__main__':
    motionapp_gui.start_up()





